# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   run_build:
#     name: run build
#     runs-on: ubuntu-latest

#     steps:
#     - name: install ssh keys
#       # check this thread to understand why its needed:
#       # https://stackoverflow.com/a/70447517
#       run: |
#         install -m 600 -D /dev/null ~/.ssh/id_rsa
#         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#         ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
#     - name: pull remote changes
#       # Source: https://stackoverflow.com/questions/4157189/how-to-git-pull-while-ignoring-local-changes
#       run: ssh ${{ vars.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ vars.WORK_DIR }} && git checkout ${{ vars.MAIN_BRANCH }} && git fetch --all && git reset --hard origin/main && git pull --ff-only"
#     - name: build
#       run: ssh ${{ vars.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ vars.WORK_DIR }} && ${{ vars.CARGO_LOCATION }} leptos build --release"
#     - name: cleanup
#       run: rm -rf ~/.ssh

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without
# warning.

# source: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  # release:
  #     types: [published]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.3.0
        with:
          images: laxsjo/lax-utils

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
