name: Deploy Docker Image to Server

on:
  workflow_run:
    workflows:
      - "Publish Docker Image"
  workflow_dispatch:

jobs:
  update_server_container:
    name: Update Docker Container on Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          # PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S docker stop lax-utils
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S docker rm lax-utils
            echo "${{ secrets.USER_PASSWORD }}" | sudo -S docker run -dp 8080:8080 --restart unless-stopped --name lax-utils laxsjo/lax-utils
